import { useEffect } from "react"
import { Link } from "react-router-dom";
export default function Privacy() {
    useEffect(() => {
        document.title = "Privacy | OpenKitchen 🧑‍🍳";
        window.scrollTo(0, 0);
      }, [])
    return(
        <div className="page">
            <div className="splash">
                <h1 className="splash-text">Privacy Policy</h1>
                <p>Last edited: 07/11/2023</p>
            </div>
            <div className="privacy-container">
                <div className="privacy">
                    <h2>1. Introduction</h2>
                    <p>OpenKitchen (alternatively "SoupGang", "us", "we", "our") operates https://openkitchen.com and its mobile application (herein referred to as "<b>Service"</b>).</p>
                    <p>Our Privacy Policy governs your visit to https://openkitchen.com and OpenKitchen mobile application, and explains how we collect, safeguard and disclose information that results from your use of our Service.</p>
                    <p>We use your data to provide and improve our Service. By using our Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</p>
                    <p>Our Terms and Conditions ("<b>Terms</b>") govern all use of our Service and together with the Privacy Policy constitutes your agreement with us ("<b>Agreement</b>").</p>    
                    
                    <h2>2. Definitions</h2>
                    <p>SERVICE means the https://openkitchen.com website, and OpenKitchen mobile application (operated by OPENKITCHEN Inc.).</p>
                    <p>PERSONAL DATA means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</p>
                    <p>USAGE DATA is data collected automatically either generated by the use of Service or from Service infrastructure itself (for example, the duration of a page visit).</p>
                    <p>COOKIES are small files stored on your device (computer or mobile device).</p>
                    <p>DATA CONTROLLER means a natural or legal person who (either alone or jointly in common with other persons) determines th epurposes for which and the manner in which any personal data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your data.</p>
                    <p>DATA SUBJECT is any living individual who is the subject of Personal Data.</p>
                    <p>THE USER is the individual using our Service. The User corresponds to the Data Subject, who is the subject of Personal Data.</p>

                    <h2>3. Information Collection and Use</h2>
                    <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>

                    <h2>4. Types of Data Collected</h2>
                    <p><b>Personal Data</b></p>
                    <p>While using our Service, we ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("<b>Personal Data</b>"). Personally identifiable information may include, butu is not limited to:</p>
                    <p>(a) Email address</p>
                    <p>(b) First name and last name</p>
                    <p>(c) Phone number</p>
                    <p>(d) Address, State, Province, ZIP/Postal code, City</p>
                    <p>(e) Cookies and Usage Data</p>
                    <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or by emailing at support@openkitchen.com</p>

                    <p><b>Usage Data</b></p>
                    <p>We may also collect information that your browser sends whenever you visit our Service or when you access our Service by or through a mobile device ("<b>Usage Data</b>").</p>
                    <p>This Usage Data may include information such as your computer's Internet Prodocal address (IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                    <p>When you access our Service with a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile internet browser you use, unique device identifiers and other diagnostic data.</p>

                    <p><b>Location Data</b></p>
                    <p>We may store information about your location if you give us permission to do so ("<b>Location Data</b>"). We use this data to provice features of our Service, to improve and customize our Service.</p>
                    <p>You can enable or disable location services when  you use our Service at any time by way of your device settings.</p>

                    <p><b>Tracking Cookies Data</b></p>
                    <p>We use cookies and similar tracking technologies to track the activity on our Service and we hold certain information.</p>
                    <p>Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</p>
                    <p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>
                    <p>Examples of Cookies we use:</p>
                    <p>(a) <b>Session Cookie</b>s: We use Session Cookies to operate our Service.</p>
                    <p>(b) <b>Preference Cookie</b>s: We use Preference Cookies to remember your preferences and various settings.</p>
                    <p>(c) <b>Security Cookie</b>s: We use Security Cookies for security purposes.</p>
                    <p>(d) <b>Advertising Cookie</b>s: Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</p>
                    <p><b>Other Data</b></p>
                    <p>While using our Service, we may also collect the following information: gender, age, date of birth, place of birth, citizenship, registration at place of residence and actual address, telephone number (work, mobile), qualification, professional training, employment agreements, information on bonuses and ocmpensation, office location and other data.</p>

                    <h2>5. Use of Data</h2>
                    <p>OPENKITCHEN Inc. uses the collected data for various purposes:</p>
                    <p>(a) to provide and maintain our Service;</p>
                    <p>(b) to notify you about changes to our Service;</p>
                    <p>(c) to allow you to participate in interactive features of our Service when you choose to do so;</p>
                    <p>(d) to provide customer support;</p>
                    <p>(e) to gather analysis or valuable information so that we can improve our Service;</p>
                    <p>(f) to monitor the usage of our Service;</p>
                    <p>(g) to detect, prevent, and address technical issues;</p>
                    <p>(h) to fulfill any other purpose for which you provide it;</p>
                    <p>(i) to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</p>
                    <p>(j) to provide you with notices about your account and/or subscription, including expiration and renewal notices, email-instructions, etc.;</p>
                    <p>(k) to provide you with news, speical offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information;</p>
                    <p>(l) in any other way we may descrive when you provide the information;</p>
                    <p>(m) for any other purpose with your consent;</p>

                    <h2>6. Retention of Data</h2>
                    <p>We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain  your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
                    <p>Wee will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>

                    <h2>7. Transfer of Data</h2>
                    <p>Your information, including Personal Data, may be transferred to - and maintained on - computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
                    <p>If you are located outside Canada and choose to provide information to us, please note that we transfer the data, including Personal Data, to Canada and process it there.</p>
                    <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
                    <p>OPENKITCHEN Inc. will take all the steps reasonably necessary to ensure that yoru data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>

                    <h2>8. Disclosure of Data</h2>
                    <p>We may disclose personal information that we collect, or you provide:</p>
                    <p>(a) <b>Disclosure for Law Enforcement:</b><br/>Under certain circumstances, we may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities.</p>
                    <p>(b) <b>Business Transaction:</b><br/>If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data may be transferred.</p>
                    <p>(c) <b>Other cases. We may also disclose your information also:</b>
                        <p>(i) to our subsidiaries and affiliates;</p>
                        <p>(ii) to contractors, service providers, and other third parties we use to support our business;</p>
                        <p>(iii) to fulfill the purpose for which you provide it;</p>
                        <p>(iv) for the purpose of including your information on our website;</p>
                        <p>(v) for any other purpose disclosed by us when you provide the information;</p>
                        <p>(vi) with your consent in any other cases;</p>
                        <p>(vii) if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of the Company, our customers, or others;</p>
                    <p>(d) OpenKicthen's use and transfer to any other app of information received from Google APIs will adhere to <a href="https://developers.google.com/terms/api-services-user-data-policy#additional_requirements_for_specific_api_scopes" rel="noreferrer" target="_blank">Google API Services User Data Policy</a>, including the Limited Use requirements.</p>

                    <h2>9. Security of Data</h2>
                    <p>The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

                    <h2>10. Your Data Protection Rights Under General Data Protection Regulation (GDPR)</h2>
                    <p>If you are a resident of the European Union (EU) and European Economic Area (EEA), you have certain data protection rights, covered by GDPR. <br/> - See more at <a href="https://eur-lex.europa.eu/eli/reg/2016/679/oj" rel="noreferrer" target="_blank">https://eur-lex.europa.eu/eli/reg/2016/679/oj</a></p>
                    <p>We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</p>
                    <p>If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please email us at support@openkitchen.com.</p>
                    <p>In certain circumstances, you have the following data protection rights:</p>
                    <p>(a) the right to acces, update or to delete the information we have on you;</p>
                    <p>(b) the right to rectification. You have the right to have your information rectified if that information is inaccurate or incomplete;</p>
                    <p>(c) the right to object. You have the right to object to our processing of your Personal Data;</p>
                    <p>(d) the right of restriction. You have the right to request that we restrict the processing of your personal information;</p>
                    <p>(e) the right to data portability. You have the right to be provided with a copy of your Personal Data in a structure, machine-readable and commonly used format;</p>
                    <p>(f) the right to withdraw consent. You also have th eright to withdraw your consent at any time where we rely on your consent to process your personal information;</p>
                    <p>Please note that we may ask you to verify your identity before responding to such requests. Please note, we may not be able to provide Service without some necessary data.</p>
                    <p>You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>

                    <h2>11. Your Data Protection Rights under the California Privacy Protection Act (CalOPPA)</h2>
                    <p>CalOPPA is the first state law in the United States to require commercial websites and online services to post a privacy policy. The alw's reach stretches well beyond the state of California to require a person or company in the United States (and concievably the world) that operates websites collecting personally identifiable information from California consumers to post a conspicuous privacy policy on its website stating exactly the information being collected and those individuals with whom it is being shared, and to comply with this policy. <br/>- See more at <a href="https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/" rel="noreferrer" target="_blank">https://consumercal.org/about-cfc/cfc-education-foundation/california-online-privacy-protection-act-caloppa-3/</a></p>
                    <p>According to CalOPPA we aggree to the following:</p>
                    <p>(a) users can visit our site anonymously;</p>
                    <p>(b) our Privacy Policy link includes the word "Privacy", and can easily be found on the page specified above on the home page of our website;</p>
                    <p>(c) users will be notified of any privacy changes on our Privacy Policy Page;</p>
                    <p>(d) users are able to change their personal information by emailing us at support@openkitchen.com</p>
                    <p>Our Policy on "Do Not Track" Signalss:</p>
                    <p>We honour Do Not Track signals and do not track, plant cookies, or use advertising when a Do Not Track browser mechanism is in place. Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.</p>
                    <p>You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.</p>

                    <h2>12. Your Data Protection Rights under the California Consumer Privacy Act (CCPA)</h2>
                    <p>If you are a California resident, you are entitled to learn what data we collect about you, ask to delete your data and not to sell (share) it. To exercise your data protection rights, you can make certain requests and ask us:</p>
                    <p>(a) What personal information we have about you. If you make this request, we will return to you:</p>
                        <p>i. The categories of personal information we have collected about you.</p>
                        <p>ii. The categories of sources from which we collect your personal information.</p>
                        <p>iii. The business or commercial purpose for collecting or selling your personal information.</p>
                        <p>iv. The categories of third parties with whom we share personal information.</p>
                        <p>v. The specific pieces of personal information we have collected about you.</p>
                        <p>vi. A list of categories of personal information that we have sold, along with the category of any other company we sold it to. If we have notsold your personal information, we will inform you of that fact.</p>
                        <p>vii. A list of categories of personal information that we have disclosed for a business purpose, along with the category of any other company we shared it with.</p>
                    </p>
                    <p>Please note, you are entitled to ask us to provide you with this information up to two times in a rolling twelve-month period. When you make this request, the information provided may be limited to the personal information we collected about you in the previous 12 months.</p>
                    <p>(b) To delete your personal information. If you make this request, we will delete the personal information we hold about you as of the date of your request form our records and direct any service providers to do the same. In some cases, deletion may be accomplished through de-identification of the information. If you choose to delete your personal information, you may not be able to use certain functions that require your personal information to operate.</p>
                    <p>(c) To stop selling your personal information. We don't sell or rent your personal information to any third parties for any purpose. You are the only owner of your Personal Data and can request disclosure or deletion at any time.</p>
                    <p>Please note, if you ask us to delete or stop selling your data, it may impact your experience with us, and you may not be able to participate in dertain programs or membership services which require the usage of your personal information to function. But in no circumstances, we will discriminate against you for exercising your rights.</p>
                    <p>To exercise your California data protection rights described above, please send your request(s) by one of the following means:</p>
                    <p>By email: support@openkitchen.com</p>
                    <p>By visiting this page on our website: <Link to="/contact">https://openkitchen.com/contact</Link></p>
                    <p>Your data protection rights, described above, are covered by the CCPA, short for the California Consumer Privacy Act. To find out more, visit the official California Legislative Information website. The CCPA took effect on 01/01/2020.</p>

                    <h2>13. Service Providers</h2>
                    <p>We may employ third party companies and individuals to facilitate our Service, provide Service on our behalf, perform Service-related services or assis us in analysing how our Service is used.</p>
                    <p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>

                    <h2>14. Analytics</h2>
                    <p>We may use third-party Service Providers to moniter and analyze the use of our Service.</p>
                    <p><b>Google Analytics</b></p>
                    <p>Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualise and personalise the ads of its own advertising network.</p>
                    <p>For more information on the privacy practices of Google, please visit the Google Privacy Terms web page: <a href="https://policies.google.com/privacy?hl=en" rel="noreferrer" target="_blank">https://policies.google.com/privacy?hl=en</a></p>
                    <p>We also encourage you to review Google's policy for safeguarding your data: <a href="https://support.google.com/analytics/answer/6004245" rel="noreferrer" target="_blank">https://support.google.com/analytics/answer/6004245</a></p>

                    <h2>15. Behavioural Remarketing</h2>
                    <p>OPENKITCHEN Inc. uses remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimize, and serve ads based on your past visits to our Service.</p>
                    <p><b>Google Ads (AdWords)</b></p>
                    <p>Google Ads (AdWords) remarketing service provided by Google Inc.</p>
                    <p>You can opt-out of Google Analytics for Display Advertising and customise the Google Display Network ads by visiting the Google Ads Settings page: <a href="https://www.google.com/settings/ads" rel="noreferrer" target="_blank">https://www.google.com/settings/ads</a></p>
                    <p>You can learn more about the privacy practices and policies of Microsoft by visiting their Privacy Policy page: <a href="https://privacy.microsoft.com/en-us/PrivacyStatement" rel="noreferrer" target="_blank">https://privacy.microsoft.com/en-us/PrivacyStatement</a></p>
                    <p><b>Twitter</b></p>
                    <p>Twitter remarketing is provided by Twitter Inc.</p>
                    <p>You can opt-out from Twitter's interest-based ads by following their instructions: <a href="https://support.twitter.com/articles/20170405" rel="noreferrer" target="_blank">https://support.twitter.com/articles/20170405</a></p>
                    <p>You can learn more about the privacy practices and policies of Twitter by visiting their Privacy Policy page: <a href="https://twitter.com/privacy" rel="noreferrer" target="_blank">https://twitter.com/privacy</a></p>
                    <p><b>Facebook</b></p>
                    <p>Facebook remarketing service is provided by Facebook Inc.</p>
                    <p>You can learn more about interest-based advertising from Facebook by visiting this page: <a href="https://www.facebook.com/help/164968693837950" rel="noreferrer" target="_blank">https://www.facebook.com/help/164968693837950</a></p>
                    <p>To opt-out from Facebook's interest-based ads, follow these instructions from Facebook: <a href="https://www.facebook.com/help/568137493302217" rel="noreferrer" target="_blank">https://www.facebook.com/help/568137493302217</a></p>
                    <p>Facebook adheres to the Self-Regulatory Principles for Online Behavioural Advertising established by the Digital Advertising Alliance. You can also opt-out from Facebook and other participating companies through the <a href="http://www.aboutads.info/choices/" rel="noreferrer" target="_blank">Digital Advertising Alliance</a>in the USA, the <a href="http://youradchoices.ca/" rel="noreferrer" target="_blank">Digital Alliance of Canada</a> in Canada, or the <a href="http://www.youronlinechoices.eu/" rel="noreferrer" target="_blank">European Interactive Digital Advertising Alliance</a> in Europe, or opt-out using your mobile device settings.</p>

                    <h2>16. Payments</h2>
                    <p>We may provide paid products and/pr services within Service. In that case, we use third-party services for payment procesing (e.g. payment processors).</p>
                    <p>We will not store or collect your payment card details. That information is provided directly to our third party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the pCI Security Standards Council, which is a joint effort of brans like Visa, Mastercard, American Express, and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>
                    <p>The payment processors we work with are:</p>
                    <p><b>Paypal or Braintree:</b></p>
                    <p>Their privacy policy can be viewed at: <a href="https://www.paypal.com/webapps/mpp/ua/privacy-full" rel="noreferrer" target="_blank">https://www.paypal.com/webapps/mpp/ua/privacy-full</a></p>
                    <p><b>Stripe:</b></p>
                    <p>Their Privacy Policy can be viewed at: <a href="https://stripe.com/privacy" rel="noreferrer" target="_blank">https://stripe.com/privacy</a></p>
                    <p><b>Square:</b></p>
                    <p>Their Privacy Policy can be viewed at: <a href="https://squareup.com/ca/en/legal/general/privacy" rel="noreferrer" target="_blank">https://squareup.com/ca/en/legal/general/privacy</a></p>

                    <h2>17. Links to Other Sites</h2>
                    <p>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
                    <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

                    <h2>18. Children's Privacy</h2>
                    <p>Our services are not intended for use by children under the age of 18 ("Child" or "Children").</p>
                    <p>We do not knowingly collect personally identifiable information from Children under 18. If you become aware that a Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from Children without verification of parental consent, we take steps to remove that information from our servers.</p>

                    <h2>19. Changes to This Privacy Policy</h2>
                    <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
                    <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this Page.</p>

                    <h2>20. Contact Us</h2>
                    <p>If you have any questions about this Privacy Policy, please contact us:</p>
                    <p>By email: privacy@openkitchen.com</p>

                    <h2>Manage My Privacy</h2>
                    <p>Use this link to manage your privacy preferencess: <Link to="/account">My Account</Link></p>
                </div>
                
            </div>
        </div>
    )
}